### ISSUE TITLE
Image decompressing in a strange way

### ISSUE THREAD

**Issue by Greenbald** [mkpaszkiewicz/image-compression#1]
Hey, when I decompress the image, the result is strange, is it expected? It seems like the result image does not have 24 bits for RGB even setting the "bits" for 8. The result image seems creepy...

Anyway, there's a way to make your code work for multilayer and kohonen?

**Comment by mkpaszkiewicz** [comment]
Hi there! Well, it is not expected that result image looks strange. I came up with the idea that maybe your training or test image are not .bmp files or just neural network is not well trained. Default options should work fine, but maybe not good enough for you case. 

Below you can find images which I used to test. 
[images.zip](https://github.com/mkpaszkiewicz/image-compression/files/389025/images.zip)

Regarding to your second question. Code will work for multilayer. In `NeuralNetwork` constructor you can find parameters `input_layer_size, hidden_layers_sizes, output_layer_size`. For example, if you set it as `5, [3, 5, 3], 5` in result you will get 5-layer network with given number of neurons.

**Comment by Greenbald** [comment]
Nice, really thank you! Where did you learn to make this compressor? It was from some class in College or bu yourself? Because I am in a class of neural networks right now, the final assignment is to make one compressor using multilayer network and kohonen, but the teacher does not offer any clue on how to do that, so I am very lost. Do you have any paper, or text that you looked on how to make one compressor?

Just one more question, as I ubderstood, you save the intput widths from the output layer, is that right? So, this informativo is used to make the conpression. But I didnt understand how you save the data, you used a function called "quantify" that I did not understand very well. 

Thanks in advance

**Comment by mkpaszkiewicz** [comment]
This project is an assignment for artificial intelligence class at university and mostly it is based on this paper
https://cs.stanford.edu/people/eroberts/courses/soco/projects/neural-networks/Applications/imagecompression.html
There it is very well described. In a shortcut. The information to make compression comes from hidden layer. Then the output of hidden layer is quantized and we get compressed image. To get decompressed image, we do reverse operation and count the output of output layer.
